language: php

before_script:
  - chmod a+x ./tests/install-php-extension.sh
  - ./tests/install-php-extension.sh  
  - composer self-update
  - composer update --dev -o --no-interaction

php:
  - 5.4
  - 5.5
  - 5.6

install:
 - composer --prefer-source install

script:
 - vendor/bin/phpcs --standard=PSR2 --report=emacs --extensions=php --warning-severity=0 --ignore=app/cache app/
 - vendor/bin/codecept run --debug
notifications:
  email:
    - fcduythien@gmail.com
